penambahan validasi admin di folder resources/views/user/TambahDataPe…
webuniska/praktikum pull request #4
Opened 2018-02-21 07:22 UTC by admblack97

…riode.blade.php bagian periode.

2018-02-22 00:25 UTC, faruq-rahmadani commented
ini sdh selesai kah?

2018-02-23 13:31 UTC, admblack97 commented
sdh

2018-02-24 07:29 UTC, FaruqRahmadani commented
di periodenya aja kah ni? kalo iya kena ku cek

2018-02-25 18:24 UTC, faruq-rahmadani requested changes

2018-02-25 18:24 UTC, FaruqRahmadani commented on resources/views/user/TambahDataPeriode.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="namaperiode" required pattern="(/[a-z0-9]\s)(/[A-Z0-9]\s).{0,}+" title="Format penulisan periode yang benar, cont
kada berasa patternnya, sama ay kaya kd be pattern. coba tulis `&` aja tetap mau

2018-02-25 18:24 UTC, FaruqRahmadani commented on resources/views/user/TambahDataPeriode.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="namaperiode" required pattern="(/[a-z0-9]\s)(/[A-Z0-9]\s).{0,}+" title="Format penulisan periode yang benar, cont
lwn validasi sagan edit datanya mana

2018-02-27 13:21 UTC, faruq-rahmadani commented
![image](https://user-images.githubusercontent.com/11961119/36730944-1cb04426-1c04-11e8-925c-96ba8b64ebf6.png)

simbol lolos validasi

2018-02-27 13:22 UTC, faruq-rahmadani requested changes

2018-02-27 13:22 UTC, faruq-rahmadani commented on resources/views/user/EditDataPeriode.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="namaperiode" value="{{$Periode->namaperiode}}" required pattern="[/a-zA-Z0-9\s]+" title="Format penulisan periode
validasi coba jadikan :  [a-zA-Z0-9/]

@admblack97

2018-02-27 14:50 UTC, admblack97 commented on resources/views/user/EditDataPeriode.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="namaperiode" value="{{$Periode->namaperiode}}" required pattern="[/a-zA-Z0-9\s]+" title="Format penulisan periode
aku mencobai mau ja validasi nya,  simbol kd tebaca

2018-02-27 14:54 UTC, admblack97 commented
![2018-02-27 1](https://user-images.githubusercontent.com/31300808/36735389-b0f89422-1c08-11e8-8f47-b7f5dda2f46d.png)

mau ja validasi nya

2018-02-27 14:55 UTC, admblack97 commented
![2018-02-27 2](https://user-images.githubusercontent.com/31300808/36735446-d461a39a-1c08-11e8-86d0-bd64029818d5.png)

yg di edit periode mau ja

2018-02-27 15:06 UTC, FaruqRahmadani commented
lah kn malah kd boleh simbol?

2018-02-27 15:07 UTC, FaruqRahmadani commented on resources/views/user/EditDataPeriode.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="namaperiode" value="{{$Periode->namaperiode}}" required pattern="[/a-zA-Z0-9\s]+" title="Format penulisan periode
yg ada ni kah?

2018-03-02 02:01 UTC, merged