Pembuatan Data User
webuniska/praktikum pull request #5
Opened 2018-02-21 14:40 UTC by admblack97

2018-02-23 13:07 UTC, FaruqRahmadani commented
yg lainnya belum kah? yg ada adminnya aja ni

2018-02-23 13:33 UTC, admblack97 commented
yg lain blm, data admin blm be validasi jua, form di tambah data admin nya sdh bujur lah, kalo pang ada yg ditambah atau dikurangi

2018-02-23 14:09 UTC, FaruqRahmadani commented
di olah kan ni backendnya, ikm tmbah akn dlu yg user lainnya

2018-02-23 16:29 UTC, faruq-rahmadani requested changes

2018-02-23 16:29 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="password" required>
typenya ganti password

2018-02-23 16:30 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="password" required>
@admblack97

2018-02-23 17:43 UTC, faruq-rahmadani requested changes
Penting !

2018-02-23 17:43 UTC, FaruqRahmadani commented on app/Http/Controllers/UserController.php
> +    $this->validate($request, [
harus diperbaiki validasinya, sesuai kan kaedah2 di : [https://laravel.com/docs/5.6/validation#rule-unique](url)

http://prntscr.com/iitmr6

2018-02-24 01:23 UTC, FaruqRahmadani commented
di sini kita olah sagan adminnya aja lah. mahasiswanya olah branch belain kena.
ini tinggal tambahi validasi, validasinya kira2 umpati aja lwn register. @admblack97 tambah akan validasinya.

2018-02-24 01:26 UTC, admblack97 commented
berarti data mahasiswa nya meulah branch beasa??

2018-02-24 01:28 UTC, FaruqRahmadani commented
iya olah beasa aja, ini fokus kn ke admin dulu. kita bereskan dulu ini

2018-02-24 01:34 UTC, admblack97 commented
untuk validasi data admin bikin branch beasa atau gabung disini ja??

2018-02-24 01:49 UTC, FaruqRahmadani commented
gabung aja, sama2 data admin jua

2018-02-24 02:08 UTC, faruq-rahmadani requested changes

2018-02-24 02:08 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="email" value="{{old('email')}}" required>
input type email

2018-02-24 02:10 UTC, faruq-rahmadani requested changes

2018-02-24 02:10 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spasi">
titlenya tambahi minimal 6 karakter

2018-02-24 02:43 UTC, FaruqRahmadani commented
@admblack97 validasi edit data adminnya dam

2018-02-24 02:43 UTC, FaruqRahmadani commented
sekalian png cek akan semuaan data admin ni jalan aja kah? kalo ada bug tolong di padahi jua

summon jg : @cumie

2018-02-24 07:28 UTC, faruq-rahmadani requested changes

2018-02-24 07:28 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{old('username')}}" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spas
simbol2nya kada usah gin, padahi minimal 6 karakter aja

2018-02-24 07:28 UTC, FaruqRahmadani commented on resources/views/user/EditDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{$Admin->User->username}}" required pattern="^[A-Za-z0-9_.]{6,}$" title="Input tidak menggunaka
sama ini jua, simbol kada usah

2018-02-24 11:19 UTC, admblack97 commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{old('username')}}" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spas
berarti validasi sebelum nya ku edit beasa

2018-02-24 11:25 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{old('username')}}" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spas
sebelumnya kyp tadih?

2018-02-24 11:35 UTC, faruq-rahmadani requested changes

2018-02-24 11:35 UTC, FaruqRahmadani commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{old('username')}}" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spas
ini jua dam @admblack97

2018-02-24 11:39 UTC, admblack97 commented on resources/views/user/TambahDataAdmin.blade.php
> +                    <input type="text" class="form-control col-md-12 col-xs-12" name="username" value="{{old('username')}}" required pattern="^[A-Za-z0-9_.,]{6,}$" title="Input tidak menggunakan spas
sebelum nya pakai simbol jua validasi username nya

2018-02-24 11:44 UTC, faruq-rahmadani approved these changes

2018-02-24 11:47 UTC, merged